### PR TITLE
Assignees of the origin MR are also cascade responsible

### LINKED ISSUE #13: Assign a failing cascade MR to all original assignee users as well
When there is a conflict, `ucascade` is assigning the MR to the person who has merged the MR.

It could assign it to all original assignee users in addition to the user who has merged the MR.

### PR DESCRIPTION
**Pull request by fbpe**
Fixes #13 

The assignees of the MR that originated the cascade are now also considered cascade responsible, in addition to the user that merged it.

### CODE REVIEW

File: src/main/java/service/GitLabService.java [hunk 1]
```diff
@@ -400,15 +404,18 @@ private MergeRequestResult acceptAutoMergeRequest(String gitlabEventUUID, MergeR
...
 		final Long project = mr.getProjectId();
-		Long cascadeResponsibleId = getCascadeResponsible(gitlabEventUUID, project, getPrevMergeRequestNumber(mr.getSourceBranch()));
-		if (cascadeResponsibleId != null) {
-			Log.infof("GitlabEvent: '%s' | Assigning MR '!%d' to cascade responsible with id '%d'", gitlabEventUUID, mrNumber, cascadeResponsibleId);
+		List<Long> cascadeResponsibleIds = getCascadeResponsibleIds(gitlabEventUUID, project, getPrevMergeRequestNumber(mr.getSourceBranch()));
+		if (cascadeResponsibleIds != null) {
+			Log.infof("GitlabEvent: '%s' | Assigning MR '!%d' to cascade responsible(s) with id(s): '%s'",
+					gitlabEventUUID,
+					mrNumber,
+					cascadeResponsibleIds.stream().map(String::valueOf).collect(Collectors.joining("', '")));
```
Comment (jmini) [inline src/main/java/service/GitLabService.java]: Isn't the logger displaying correctly a `List<Long>` already? In that case you do not need this conversion with the steam api.

File: src/main/java/service/GitLabService.java [hunk 2]
```diff
@@ -504,31 +511,38 @@ private boolean haveDiff(String gitlabEventUUID, Long project, String from, Stri
...
+		}
+
+		Long mrMerger = mr.getMergeUser().getId();
+		Log.infof("GitlabEvent: '%s' | MR merger has id '%d', ucascade user has id '%d'", gitlabEventUUID, mrMerger, ucascadeUser);
+
+		if (!Objects.equals(mrMerger, ucascadeUser)) {
+			// success exit point, found the origin mr
+			List<Long> cascadeResponsibleIds = mr.getAssignees().stream().map(Assignee::getId).collect(Collectors.toList());
+			if (!cascadeResponsibleIds.contains(mrMerger)) {
+				cascadeResponsibleIds.add(mrMerger);
```
Comment (jmini) [inline src/main/java/service/GitLabService.java:525]: I don't think that the list obtained with `.collect(Collectors.toList())` is mutable.

Are you sure this works?

**Review by jmini — COMMENTED** [review]
Looks good to me, just two points where I am not sure.

File: src/main/java/service/GitLabService.java (hunk 2 above)
Comment (fbpe) [reply src/main/java/service/GitLabService.java:525]: > I don't think that the list obtained with .collect(Collectors.toList()) is mutable.

I am using `.collect(Collectors.toList())` instead of just the `.toList()` (from Stream) precisely to make it mutable. Maybe you are confusing the two? 

I might be missing something but this seems to work well. Are you thinking of a special case?

Ref: https://www.javacodegeeks.com/2020/12/jdk-16-stream-to-list-in-one-easy-call.html

File: src/main/java/service/GitLabService.java (hunk 1 above)
Comment (fbpe) [reply src/main/java/service/GitLabService.java]: Good point, yes! Thank you, I changed it accordingly.

File: src/main/java/service/GitLabService.java (hunk 2 above)
Comment (jmini) [reply src/main/java/service/GitLabService.java:525]: Ok for me both were equivalent… I thought `Collectors.toList()` is creating an immutable list.

**Review by jmini — APPROVED** [review]
